# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f586e8198d49bdc6cdb630315c865f704163be5f9a7f98274bafc2bbcf7bd6c9bc0d3aff7cec49214d113f6ee7f00f366e66d0c3bc461c6af4f5a598f64f52e0

test:
  secret_key_base: 8d97f900841df8e1ea427ee40e6182ab29d9c22b45d3943c0bc4c7cc0e187e5e5be6786dbf28a4a3f810540efecf228069293c0c856fca9dcdbc1fd1b5971c58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
